<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{b39c4d0b-2cf0-453e-b50b-5dbaaa464394}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	stMyTest : ST_Convert ;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

PRG_PowerMeter() ;

PRG_Database();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>